<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace dssource\basic\core;


use Yii;
use yii\db\ActiveRecord;

class BasePage extends ActiveRecord
{
    const NO_IMAGE = 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iNjI0IiBoZWlnaHQ9IjUxMiIgdmlld0JveD0iMCAwIDYyNCA1MTIiPjxnIGlkPSJpY29tb29uLWlnbm9yZSI+PC9nPjxwYXRoIGZpbGw9IiNFNUUzRTMiIGQ9Ik0yLjc0NyAzLjU2NnY1MDQuODdoNjIxLjM3OXYtNTA0Ljg3aC02MjEuMzc5ek01ODUuMjg5IDQ2OS41OTloLTU0My43MDZ2LTQyNy4xOTdoNTQzLjcwNnY0MjcuMTk3ek00MjkuOTQ1IDEzOS40OTJjMCAzMi4xNzMgMjYuMDgwIDU4LjI1NSA1OC4yNTUgNTguMjU1czU4LjI1NC0yNi4wODEgNTguMjU0LTU4LjI1NS0yNi4wODEtNTguMjU1LTU4LjI1NS01OC4yNTUtNTguMjU1IDI2LjA4MS01OC4yNTUgNTguMjU1ek01NDYuNDUzIDQzMC43NjJoLTQ2Ni4wMzRsMTE2LjUwOC0zMTAuNjg5IDE1NS4zNDUgMTk0LjE4MSA3Ny42NzItNTguMjU1IDExNi41MDkgMTc0Ljc2MnoiPjwvcGF0aD48L3N2Zz4=';

    public $imageFile;
    public $imageUploadPath = 'files/pages';
    private $_cache;
    public $sectionClassName = 'dssource\basic\core\BaseSection';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->class = $this->className();
    }

    public static function tableName()
    {
        return 'ds_site_pages';
    }

    public function getSection()
    {
        return $this->hasOne($this->sectionClassName, ['id' => 'id_section']);
    }

    public static function find($condition = false)
    {
        return $condition ? parent::find()->where(['class' => self::className()])->andWhere($condition) : parent::find()->where(['class' => self::className()]);
    }

    public function getFieldById($field, $id)
    {
        if(isset($this->_cache[$id])) return $this->_cache[$id]->attributes[$field];
        else
        {
            $item = static::findOne($id);
            if($item == null) return false;
            else
            {
                $this->_cache[$id] = $item;
                return $item->attributes[$field];
            }
        }
    }

    public function getPublish()
    {
        if($this->is_publish)
            return true;
        else
            return false;
    }

    public function getImageUrl()
    {
        if($this->image != '')
            return (substr($this->image,0,4) == 'data' ? $this->image : '/'.Yii::getAlias('@web').$this->image);
        else
            return self::NO_IMAGE;
    }

    public function getRootUrl()
    {
        $protocol = ((!empty(getenv('HTTPS')) && getenv('HTTPS') != 'off') ||
            getenv('SERVER_PORT') == 443) ? "https://" : "http://";

        return $protocol.getenv('HTTP_HOST');
    }

    public function getUrl()
    {
        return '/'.($this->section->id == 1 ? '' : $this->section->getFullUrlPath().'/' ).$this->alias.'.html';
    }

    public function getAbsoluteUrl()
    {
        return $this->getRootUrl().$this->getUrl();
    }

    public function getFullPath()
    {
        return $this->section->fullPath;
    }

    public function getBreadcrumbs()
    {
        return $this->section->getBreadcrumbs(true);
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'image' => 'Картинка',
            'imageFile' => 'Картинка',
            'name' => 'Имя',
            'alias' => 'Алиас (URL)',
            'content' => 'Содержание',
            'id_section' => 'Раздел',
            'short' => 'Краткий текст',
            'keywords' => 'Ключевые слова',
            'is_publish' => 'Опубликовано',
            'vk_import' => 'ВК Пост',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        Yii::$app->getSession()->setFlash('success', 'Раздел создан');
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['name', 'alias', 'id_section'], 'required'],
            ['id_section', 'integer'],
            ['is_publish', 'boolean'],
            [['short', 'content', 'keywords', 'vk_post'], 'safe'],
            ['class', 'safe']
        ];
    }

    public function uploadImage()
    {
        $newName = date('dmyhis').'_page.'.strtolower($this->imageFile->extension);

        $newName = $this->imageUploadPath.'/'.$newName;

        $this->imageFile->saveAs(Yii::getAlias('@webroot').'/' .$newName);
        $this->image = $newName;
        return true;
    }
}