<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace dssource\basic\widgets;
use Yii;
use dssource\basic\widgets\assets\RedactorAsset;
use yii\widgets\InputWidget;
use yii\helpers\Html;

class Redactor extends InputWidget
{
    private $type = 'text';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $view = Yii::$app->getView();
        $this->registerAssets();
        $view->registerJs($this->getJs());
        //$this->options['class'] = 'form-control';
    }

    public function run()
    {
        if ($this->hasModel()) {
            //return var_dump($this->model);
            return Html::activeTextarea($this->model, $this->attribute, $this->options);
        }
        return Html::textarea($this->name, $this->value, $this->options);
    }

    public function registerAssets()
    {
        $view = $this->getView();
        RedactorAsset::register($view);
    }

    public function getJS()
    {
        $elementId = $this->options['id'];
        $js = <<<JS
        $("document").ready(function(){
        console.log("Widget Redactor active!");
        CKEDITOR.replace("$elementId", {
         uiColor: '#313335'
        });
        });
JS;

        return $js;
    }
}