<?php

namespace dssource\basic\assets\dracula;

use Yii;
use yii\web\AssetBundle;
use dssource\basic\core\Themes;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class BasicAsset extends AssetBundle
{
    public $sourcePath;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = Themes::activeThemeRootPath().'/res/general';
    }

    public $css = [
        'css/bootstrap-theme.css',
    ];
    public $js = [
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];
}
