<?php

namespace dssource\basic\assets\dracula;

use yii\web\AssetBundle;
use dssource\basic\core\Themes;

class PageViewAsset extends AssetBundle
{
    public $sourcePath;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = Themes::activeThemeRootPath().'/res/admin';
    }

    public $css = [
        'ckeditor/plugins/codesnippet/lib/highlight/styles/tomorrow-night-eighties.css',
    ];
    public $js = [
        'ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js',
        'ckeditor/initCodeSnippet.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    /*
     * <script>hljs.initHighlightingOnLoad();</script>
     */
}
