<?php

namespace dssource\basic\assets\dracula;

use yii\web\AssetBundle;
use dssource\basic\core\Themes;

/**
 * Main application asset bundle.
 *
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class RedactorAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = Themes::activeThemeRootPath().'/res/admin';
    }

    //public $css = [
    //    'css/site.css',
    //];
    public $js = [
        'ckeditor/ckeditor.js'
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];
}
