<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace dssource\basic\models;

use yii\helpers\ArrayHelper;
use dssource\basic\core\BasePage;
use dssource\basic\models\Section;


class Page extends BasePage {

    public $sectionClassName = 'dssource\basic\models\Section';

    //public function getSection()
    //{
    //    return $this->hasOne(Section::className(), ['id' => 'id_section']);
    //}

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sectionClassName = Section::className();
    }

    public function sectionList()
    {
        return ArrayHelper::map(Section::find()->all(), 'id', 'name');
    }
}