<?php
/**
 * Created by Digital-Solution.Ru web-studio.
 * https://digital-solution.ru
 * support@digital-solution.ru
 */

namespace dssource\basic\models;
use Yii;
use dssource\basic\core\BaseSection;


class Section extends BaseSection {

    public $uploadImagePath = 'files/sections';
    const SCENARIO_SECTION_FOR_PAGES = 'pages';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getPages()
    {
        return $this->hasMany(Page::className(),['id_section' => 'id']);
    }

    public function sections($class = false)
    {
        if(!$class)
            return static::find()->all();
        else
            return static::find()->where(['class' => $class])->all();
    }

    public function rules()
    {
        return [
            ['class', 'default', 'value' => self::className()],
            [['name', 'alias', 'class'], 'required', 'on' => self::SCENARIO_SECTION_FOR_PAGES],
            [['name','alias'], 'unique'],
            [['description','isParent', 'id_parent', 'show_in_catalog'], 'safe'],

        ];
    }

    public function beforeSave($insert)
    {
        if($this->isParent == 1)
            $this->id_parent = 0;
        //exit(var_dump($this));
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        Yii::$app->getSession()->setFlash('success', 'Раздел создан');
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


}